---
title: "Data Normalization"
author: "Brandon Chung"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
```

#Cleaning job_skills CSV
```{r}
job_skill<-"https://raw.githubusercontent.com/stephbc/DATA607-Project3/refs/heads/main/job_skills.csv"

df<-read.csv(job_skill, sep=',')
nrow(df) #12217

#create a function to extract the ID numbers from the job_link:
id<- function(df) {
  stringr::str_extract(df, "(\\d)+$")
}
#transform and rename job_link to job_ID:
df$job_link<-id(df$job_link)
names(df)[names(df)=='job_link'] <-"job_ID"

#remove empty cells:
df<- na.omit(if_else(df$job_skills=="", NA, df))
nrow(df) #12212

#separate the skills:
df_mod<- df %>%
  separate_wider_delim(job_skills, delim=',',
                       names_sep = '_',
                       too_few = 'align_start')


#Select only the first 20 skills listed:
df_mod_20<- df_mod %>%
  subset(select = c(1:21))


#pivot_longer to put all skills into one column:
df_mod_long<- df_mod_20 %>%
  pivot_longer(cols = c(2:21), #This is where we can adjust how many columns we want to include. Too many will cause loading issue.
               names_to = 'sets',
               values_to = 'Skills',
               values_drop_na = TRUE)
  
#remove 'sets' column:
df_mod_long<- df_mod_long%>%
  subset(select = c(job_ID, Skills))


df_mod_long <- df_mod_long %>%
  mutate(Skills = str_trim(Skills))

df_skills<-data.frame('Skills'=trimws(df_mod_long$Skills))
```

#Creating Skills Table
```{r}
# Count the frequency of each skill
skill_counts <- df_skills %>%
  count(Skills, sort = TRUE) %>%
  top_n(100, n) %>%
  mutate(identifier = row_number())

skill_counts <- skill_counts %>%
  rename(skill_id = identifier) %>%
  relocate(skill_id, .before = 1) 

skill_counts <- skill_counts[,-3]

Skills <- skill_counts
```

#Creating Listing_Skills Table
```{r}
Listing_Skills <- inner_join(Skills, df_mod_long, by = "Skills")

Listing_Skills <- Listing_Skills %>%
  relocate(job_ID, .before = 1)

Listing_Skills <- Listing_Skills[,-3] 

```
#Cleaning job_postings CSV

```{r}
job_posting<- "https://raw.githubusercontent.com/stormwhale/data-mines/refs/heads/main/job_postings.csv"

df2<-read.csv(job_posting, header=TRUE, sep = ',')

#delete irrelevant columns:
df2<-df2[-c(3:6, 10:11)]
```

```{r}
#normalize location data:
norm_df2<- df2 %>%
  filter(search_country =='United States') %>%
  separate_wider_delim(cols = job_location,
                       delim=",",
                       names=c("City", "State_or_Province"),
                       too_few = 'align_start',
                       too_many = 'merge')

table(norm_df2$State_or_Province) #Few rows still have other countries.
# to further refine the data:

norm_df2<- norm_df2 %>%
  filter(!grepl("Mexico|India|Italy|Canada",
               State_or_Province,
               ignore.case=TRUE))

#Extract date from last_processing column:
norm_df2$last_process_date<- format(as.Date(norm_df2$last_processed_time), format = "%m-%d-%Y")

norm_df2<- norm_df2 %>%
  select(-c('last_processed_time', 'search_position','search_country'))

#Transform the job_link to job_ID in job_posting table:
norm_df2$job_link<- id(norm_df2$job_link)
names(norm_df2)[names(norm_df2)=='job_link']<-'job_ID'
```

#Creating Company Table
```{r}
Company <- norm_df2[,3:5]

#Removing duplicate rows across company, city, and state_or_province or company per location ID creation
Company <- Company %>%
  distinct(company, City, State_or_Province, .keep_all = TRUE) %>%
  mutate(identifier = row_number()) %>%
  relocate(identifier, .before = 1) %>%
  rename(company_id = identifier)
```

#Creating Job_Listing Table

```{r}
norm_df2 <- norm_df2[,-8]

Job_Lisitng <- norm_df2 %>%
  inner_join(Company, by = c("company", "City", "State_or_Province"))

Job_Lisitng <- Job_Lisitng[,-c(3,4,5)] 

Job_Lisitng <- Job_Lisitng %>%
  relocate(company_id, .before = 3)%>%
  relocate(job_type, .before = 4)
```









